-- Optional Supabase schema for Voice of Peace music.
-- The current music.html works immediately with browser localStorage.
-- Run this when you want additions/categories shared across devices.

create table if not exists public.voice_music_categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamptz not null default now()
);

create table if not exists public.voice_music (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text,
  category text not null,
  youtube_video_id text,
  youtube_url text,
  sort_order integer default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.voice_music_categories enable row level security;
alter table public.voice_music enable row level security;

-- Read access for the public site:
drop policy if exists "public read music categories" on public.voice_music_categories;
create policy "public read music categories"
on public.voice_music_categories for select
using (true);

drop policy if exists "public read music" on public.voice_music;
create policy "public read music"
on public.voice_music for select
using (active = true);

-- IMPORTANT:
-- Do not enable public INSERT/UPDATE/DELETE unless you also add authentication.
-- Keep admin writes protected.
